### ISSUE TITLE
Generates unnecessary sql for computed columns

### ISSUE THREAD

**Issue by kenwarner** [dnlnln/generate-sql-merge#1]
Thanks very much for providing this script. I did notice that it was generating sql for computed columns though.

**Comment by dnlnln** [comment]
Thanks Ken, glad you're finding the script useful. Will definitely have to look into this!

**Comment by dnlnln** [comment]
The `@ommit_computed_cols` parameter is now set to `1` by default, so there's no need to specify this when calling `sp_generate_merge` anymore in order to avoid the unnecessary sql from being included in the merge statement (sorry I should have mentioned that this option was available earlier!).
