### ISSUE TITLE
Make sure you have SELECT permission on that table or view.

### ISSUE THREAD

**Issue by stfarm** [dnlnln/generate-sql-merge#22]
I am sure it's just a user error, but I can't figure out what I am doing wrong. This would be the perfect script.

I want to use it for a table I have (TRAVEL.dbo.AIRLINES) for example.
I execute (I am logged in as sa):
`EXEC sp_generate_merge @schema = 'TRAVEL', @table_name ='dbo.AIRLINES'`

Then I get this error.
```
Msg 50000, Level 16, State 1, Procedure sp_generate_merge, Line 216 [Batch Start Line 0]
User table or view not found.
Make sure you have SELECT permission on that table or view.
```
I would appreciate any help.

**Comment by jakubro** [comment]
How about this
```
EXEC [Travel].[dbo].sp_generate_merge @schema = 'dbo', @table_name ='AIRLINES'
```

Notice the difference in `@schema` and `@table_name` params.

**Comment by stfarm** [comment]
So cool, thank you for the quick reply, that worked great!!
