### ISSUE TITLE
Incorrect syntax near ')' - caused by one too many on line 369

### ISSUE THREAD

**Issue by PhilipBathe** [dnlnln/generate-sql-merge#23]
Hi,

I was using this excellent sp and stumbled on an error.  I tried to use it on a table with a varbinary column (by accident, I hadn't noticed the 12th column was storing images) and received the "Incorrect syntax near ')'" error.  looking in the sp I found the WHEN statement for ('binary','varbinary') :

 WHEN @Data_Type IN ('binary','varbinary') 
 THEN 
 'COALESCE(RTRIM(CONVERT(varchar(max),' + @Column_Name + ', 1))),''NULL'')' 

The last line has one too many close brackets and should be:

 'COALESCE(RTRIM(CONVERT(varchar(max),' + @Column_Name + ', 1)),''NULL'')'

**Comment by dnlnln** [comment]
Thanks for that feedback. I'll look at fixing this in the next few days (although PRs are also welcome :))
