### ISSUE TITLE
XML parsing: illegal xml character

### ISSUE THREAD

**Issue by baur** [dnlnln/generate-sql-merge#28]
**SQL Server 2016 Express** 
Msg 9420, Level 16, State 1, Procedure sp_generate_merge, Line 540 [Batch Start Line 0] XML parsing: line 1, character 210, illegal xml character

**Comment by dnlnln** [comment]
Unfortunately I am unable reproduce this.

Can you please supply steps to cause this error?

**Comment by dnlnln** [comment]
Unable to reproduce

**Comment by TDK1964** [comment]
I also get this error now. One of my columns contains this data
ਨਲ
<
dn
xyz{
|}
xyz
GHIJ
KL
GHI
ྠ
2
­
°
®¯
ª
ÈÒÜæ
ðú
ÈÒÜ
 
¾¿ÀÁ
Ä
ÂÃ
¾¿À
]
^
Z[\
 !
"
 
q
r
n




´µ¶·
º
¸¹
´µ¶



Ĭ
翿
QRST
UV
Q
£
¥
¤
 ¡¢




ஸ
()*+




**Comment by TDK1964** [comment]
It looks like it's this line ' !' causing the problem
