### ISSUE TITLE
Declare @output & xml output as NVarchar

### ISSUE THREAD

**Issue by saorsa** [dnlnln/generate-sql-merge#3]
Hello, when using the stored procedure with cyrillic (and guess other unicode stuff), the nvarchar column values are replaced with ??.
Declaring the output variables as NVarchar should fix this.
Cheers.

**Comment by saorsa** [comment]
Also N.. column values should be prefixed with N'
Example:
values(N'кирилица'....)

**Comment by milindur** [comment]
I have the same problem. I would like to update a dictionary with localization strings, incl. Greek and Chinese.

**Comment by dnlnln** [comment]
This should now be fixed (sorry it took so long!), but if you notice any further encoding issues please let me know.
