### ISSUE TITLE
Generated MERGE statement is invalid if it includes geography type columns

### ISSUE THREAD

**Issue by shabeker** [dnlnln/generate-sql-merge#42]
Columns of type geography cannot be compared with = or NULLIF. The merge statement generated for tables that have geography columns yields the following error:
"Invalid operator for data type. Operator equals equal to, type equals geography."
Comparing geography values needs to use the STEquals() function.

**Comment by dnlnln** [comment]
I've submitted a PR to fix this issue (#44, branch: `support-geo-data-types`), as well as adding support for the geometry data-type.

If you have a chance to confirm that it fixes the problem, that'd be great!

**Comment by shabeker** [comment]
Thanks for the update! I confirm it fixes the issue.
