### ISSUE TITLE
`@cols_to_join_on` requires that `@schema` is also set

### ISSUE THREAD

**Issue by TheJayMann** [dnlnln/generate-sql-merge#48]
When `@cols_to_join_on` is specified, an error is set specifying that a valid `@cols_to_join_on` has not been set.  When explicitly specifying the schema, it works.

It appears that at line [438](https://github.com/readyroll/generate-sql-merge/blob/4392abf5d0f7718d72f3179191a3788d0fcc747f/master.dbo.sp_generate_merge.sql#L483) the filter is matching `c.TABLE_SCHEMA` to `@schema`, requiring the `@schema` parameter be defined, while on line [470](https://github.com/readyroll/generate-sql-merge/blob/4392abf5d0f7718d72f3179191a3788d0fcc747f/master.dbo.sp_generate_merge.sql#L470) the filter is matching `c.TABLE_SCHEMA` to `COALLESCE(@schema, SCHEMA_NAME())`, allowing the current schema to be used if not specified.

**Comment by dnlnln** [comment]
Good catch, this should now be fixed. Let me know if you still encounter problems with it though.
