### ISSUE TITLE
Column names and tabs

### ISSUE THREAD

**Issue by otake1977** [dnlnln/generate-sql-merge#69]
Hi,

First of all thanks for the work you have done on this.

I've been using this sometime but with the newer version, it seems we lost the column names and tabbing depending on value lengths. Was this removed in recent versions?

**Comment by dnlnln** [comment]
Sorry I'm not sure I quite follow. Do you mean the whitespace in the merge statement itself is now being formatted differently? Would definitely appreciate a before-and-after output sample if that is the case :)

**Comment by dnlnln** [comment]
Closing this as clarification was not provided
