### ISSUE TITLE
Add reference to examples in readme.md?

### ISSUE THREAD

**Issue by spottedmahn** [dnlnln/generate-sql-merge#80]
I just stumbled upon the examples in the script... what about adding a reference to those examples in the readme.md so that it is more discoverable?

Happy to submit a PR 😊

**Comment by dnlnln** [comment]
Sorry for not responding until now. That's a great idea, feel free to submit a PR to update the `readme.md`, perhaps with a new section called "More Examples"?

**Comment by spottedmahn** [comment]
No worries, it happens 😀.  Cool, I’ll give it some & report back
