### ISSUE TITLE
Case mismatch object_id column name

### ISSUE THREAD

**Issue by BHolthuijsen** [dnlnln/generate-sql-merge#92]
This is just nit-picking, no real issue for me.

During a build in VS 2022, I get the following warning:

 ```
Warning SQL71558: The object reference [sys].[identity_columns].[OBJECT_ID] differs only by case from the object definition [master].[sys].[identity_columns].[object_id].
```

The warning occurs in the following line:
https://github.com/readyroll/generate-sql-merge/blob/9e9ddd2472317d54d9a45ec81aaff5b3aa0131dc/master.dbo.sp_generate_merge.sql#L538

The "OBJECT_ID" should be changed to "object_id" to match the case of the column.

The current warning can just be ignored for me. Maybe it could be an issue in an instance that was installed as case sensitive.

**Comment by dnlnln** [comment]
This is now fixed, thanks for the report!
